- platform: template
  sensors:
    garage_position:
      friendly_name: Garage Door
      value_template: "{{ is_state('switch.garage_door_99','on')}}"
      device_class: opening
    front_hall_motion:
      friendly_name: Front Hall Motion
      value_template: "{{ is_state(input_boolean.front_hall_motion, 'on')}}"
      device_class: motion

#experimental ring doorbell

- platform: workday
  country: US
  

- platform: ring
  monitored_conditions:
    - ding
    - motion


- platform: rpi_gpio
  pull_mode: up
  ports:
    5: basement_slider_sensor
    12: back_door_slider_sensor
    13: front_door_sensor
    6: garage_door_door_sensor
    16: front_hall_motion_raw


