- platform: pi_hole
  host: 10.9.209.182:8017
  name: pihole
  
- platform: pi_hole
  host: 10.9.209.11
  name: pihole-gonzo

#- platform: yr

#- platform: speedtest
#  minute:
#    - 0
#    - 30
#  monitored_conditions:
#    - ping
#    - download
#    - upload

#- platform: wunderground
#  api_key: !secret wunderground_api_key
#  monitored_conditions:
#    - feelslike_f
#    - temp_f
#    - wind_mph
#    - weather
    
- platform: transmission
  host: !secret transmission_host
  username: !secret transmission_username
  password: !secret transmission_password
  monitored_variables:
    - current_status
    - download_speed
    - upload_speed

- platform: nzbget
  host: beaker
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - download_rate
    - uptime

- platform: template
  sensors:
    ring_motion:
      friendly_name: Front Door Motion
      value_template: '{{ states.input_boolean.ring_motion.state }}'
#    wii:
#      friendly_name: Wii
#      value_template: "{{ 'Online' if is_state('device_tracker.wii', 'home') else 'Offline' }}"
    kitchen_nest:
      friendly_name: Kitchen Nest
      value_template: "{{ 'Online' if is_state('binary_sensor.kitchen_thermostat_online', 'on') else 'OFFLINE' }}"  
    mbr_nest:
      friendly_name: MBR Nest
      value_template: "{{ 'Online' if is_state('binary_sensor.master_bedroom_thermostat_online', 'on') else 'OFFLINE' }}"
    basement_nest:
      friendly_name: Basement Nest
      value_template: "{{ 'Online' if is_state('binary_sensor.basement_thermostat_online', 'on') else 'OFFLINE' }}"
    chromecast:
      friendly_name: Chromecast
      value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'OFFLINE' }}"
    vera:
      friendly_name: Vera
      value_template: "{{ 'Online' if is_state('device_tracker.vera', 'home') else 'OFFLINE' }}"
    harmony:
      friendly_name: Family Room Hub
      value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'OFFLINE' }}"
    abby_location:
      friendly_name: Abby's Location
      value_template: "{% if is_state('states.device_tracker.abbysiphone.state', 'home' ) %} {{states.device_tracker.abbysiphone.state }} {% else %}  {{ states.device_tracker.abby_abbysiphone.state }} {% endif %}  " 
    joe_location:
      friendly_name: Joe's Location
      value_template: "{% if is_state('states.device_tracker.joes_iphone_7.state', 'home' ) %} {{states.device_tracker.joes_iphone_7.state }} {% else %}  {{ states.device_tracker.joe_iphone.state }} {% endif %}  " 
    joe_iphone_battery:
      friendly_name: Joe's Battery
      value_template: '{{ states.device_tracker.joe_iphone.attributes.battery|int }}'
      device_class: battery
      unit_of_measurement: "%"
    becca_location:
      friendly_name: Becca's Location
      value_template: "{% if is_state('states.device_tracker.device_tracker.becca_beccasiphone', 'home' ) %} {{states.device_tracker.device_tracker.becca_beccasiphone.state }} {% else %}  {{ states.device_tracker.becca_iphone.state }} {% endif %}  " 

    waqi_fredericksburg:
      friendly_name: Air Quality
      value_template: >
         {%if states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 50 %} Good
         {% elif states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 100 %} Moderate
         {% elif states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 150 %} Unhealthy for Senstive Groups
         {% elif states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 200 %} Unhealthy
         {% elif states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 250 %} Very Unhealthy 
         {% elif states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.state| int  < 300 %} Very Unhealthy
         {% else %} Dude get the fuck outta here! 
         {% endif %}
      icon_template: "{{states.sensor.waqi_widewater_elem_school__widewater_fredericksburg_usa.attributes.icon }}"
    allergy_index_forecasted_average_trend:
      friendly_name: "Allergy Index: Forecasted Average"
      value_template: "{{ states.sensor.allergy_index_forecasted_average.attributes.trend}}" 
      icon_template: "{{ states.sensor.allergy_index_forecasted_average.attributes.icon}}"
    allergy_index_today_trend:
      friendly_name: "Allergy Index: Today"
      value_template: "{{states.sensor.allergy_index_today.attributes.rating }}"
      icon_template: "{{states.sensor.allergy_index_today.attributes.icon}}"
    allergy_index_tomorrow_trend:
      friendly_name: "Allergy Index: Tomorrow"
      value_template: "{{states.sensor.allergy_index_tomorrow.attributes.rating}}"
      icon_template: "{{states.sensor.allergy_index_tomorrow.attributes.icon}}"   

- platform: mqtt
  state_topic: owntracks/Abby/abbysiphone
  name: "Abbys iPhone"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: Vera/Events/FrontDoorLock
  name: "Last Front Door code"
  value_template: >
       {% set list1=value_json.sl_UserCode.split('"')  %}
       {{ list1[3] }} 

- platform: mqtt
  state_topic: Vera/Events/FrontDoorLock
  name: "Last Front Door timestamp"
  value_template: "{{ value_json.Time }}"


- platform: sonarr
  api_key: !secret sonarr_api_key
  host: beaker
  port: 8989
  monitored_conditions:
    - upcoming
  days: 3

- platform: radarr
  api_key: !secret radarr_api_key
  host: beaker
  port: 7878
  monitored_conditions:
    - upcoming
    - status
    

- platform: waze_travel_time
  name: Home to Work
  origin: !secret home_address
  destination: !secret work_address
  region: 'US'

- platform: waze_travel_time
  name: Home to VRE lot
  origin: !secret home_address
  destination: !secret train_station_address
  region: 'US'

- platform: waze_travel_time
  name: Work to Home
  origin: !secret work_address
  destination: !secret home_address
  region: 'US'

- platform: waze_travel_time
  name: Home to Gymnastics
  origin: !secret home_address
  destination: !secret gymnastics_address
  region: 'US'

- platform: template
  sensors:
    #Family room hub current activity
    remote_activity:
      friendly_name: 'Family Room Activity:'
      value_template: '{{ states.remote.family_room.attributes.current_activity }}'
    #Basement hub current acivity
    basement_remote_activity:
      friendly_name: 'Basement Activity:'
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'

    #Front door battery levels
    front_batt_level:
      friendly_name: 'Front Door Lock'
      value_template: '{{ states.lock.front_door_lock_4.attributes.battery_level }}'
      unit_of_measurement: '%'
    window_batt_level:
      friendly_name: 'Window Sensor'
      value_template: ' {{ states.binary_sensor.mbr_window_sensor_197.attributes.battery_level }} '    
      unit_of_measurement: '%'

    #motion sensors battery level
    office_batt_level:
      friendly_name: 'Office Motion PIR'
      value_template: '{{ states.binary_sensor.office_motion_161.attributes.battery_level }}'
      unit_of_measurement: '%'
    upstairs_batt_level:
      friendly_name: 'Upstairs Hall PIR'
      value_template: '{{ states.binary_sensor.upstairs_motion_124.attributes.battery_level }}'
      unit_of_measurement: '%'
    


- platform: waqi
  token: !secret waqi_api_key
  locations:
    - fredericksburg



- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - hourly_summary
    - daily_summary
    - temperature
    - humidity
    - precip_probability
    - precip_intensity
    - wind_speed
    - pressure
    - wind_bearing
    - apparent_temperature
  update_interval: '00:15:00'


- platform: command_line
  name: CPU
  command: vmstat 1 2 | tail -1 | awk '{print int($13+$14)}'
  unit_of_measurement: "%"

- platform: command_line
  name: Disk Space used
  command: df -l --total  / | tail -1 | awk '{ print int($5) }'
  unit_of_measurement: "%"


- platform: ups
  name: 'UPS'
  username: !secret ups_username
  password: !secret ups_password


#ring doorbell
- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume


- platform: crimereports
  name: neighborhood_crime
  radius: 1000

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: uber
  server_token: !secret uber_token

- platform: season
  type: astronomical


- platform: fail2ban
  jails:
    - ssh
    - ha
  scan_interval: 60
  file_path: /var/log/fail2ban.log


- platform: pollen
  zip_code: !secret zip_code
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - disease_average_forecasted

#custom tautulli sensor
- platform: tautulli
  host: !secret tatulli_url
  ssl: true
  verify_ssl: false
  token: !secret tautulli_token
  monitored_conditions:
    - stream_count
    - stream_count_transcode
    - stream_count_direct_play
    - stream_count_direct_stream
    - total_bandwidth



#- platform: rest
#  resource: !secret joes_heroku_url
#  name: joes current BG
#  value_template: >
#        {% set temp=value.split("\t") %}
#        {{ temp[2] }}

#- platform: rest
#  resource: !secret joes_heroku_url_json
#  name: Joes BG value
#  unit_of_measurement: "mg/dL"
#  value_template: ' {{value_json[0].sgv }} '
  
#- platform: rest
#  resource: !secret joes_heroku_url_json
#  name: Joes BG direction
#  value_template: ' {{value_json[0].direction }} '

