resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.0.8
    type: js
  - url: /local/bignumber-card.js
    type: js
  - url: /local/group-card.js
    type: js
  - url: /local/monster-card.js
    type: js
  - url: /local/tracker-card.js?v=0
    type: js
    
    



title: FredVegas
views:
    # View tab title.
  - title: home
    id: 0
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - sensor.joe_location
              - device_tracker.jensiphone
              - sensor.abby_location
              - sensor.becca_location
            state_filter:
              - "home"
            card:
              type: glance
              title: Who's home?
              show_state: false
          - type: map
            entities:
              - zone.home
              - device_tracker.joe_joesiphone6s
              - device_tracker.abby_abbysiphone
              - device_tracker.becca_beccasiphone
      - type: entity-filter
        entities: 
          - binary_sensor.front_door_sensor
          - binary_sensor.garage_door_door_sensor
          - binary_sensor.back_door_slider_sensor
          - binary_sensor.basement_slider_sensor
          - binary_sensor.garage_position 
        state_filter:
          - "on"
        card:
          type: glance
          title: Doors Open
          show_state: false
          show_empty: false
      - type: entity-filter
        entities:
          - binary_sensor.office_motion_161
          - binary_sensor.upstairs_motion_124
          - binary_sensor.basement_motion_1_216
          - binary_sensor.dafang_motion_sensor	
          - binary_sensor.front_hall_motion
          - binary_sensor.ring_front_door_motion
        state_filter:
          - "on"
        card:
          type: glance
          title: Motion detected
          show_state: false
      - type: custom:monster-card
        show_empty: false
        card: 
          type: glance
          title: "Low Battery"
          show_state: false
        filter:
          include:
            - domain: binary_sensor
              attributes:
                battery_level: '< 30'
            - domain: lock
              attributes:
                battery_level: '< 30'
            - domain: device_tracker
              attributes:
                battery: '< 30'
      - type: vertical-stack
        aspect_ratio: 75%
        cards:
          - type: entities
            title: Modes
            show_header_toggle: false
            entities:
              - input_boolean.xmas_mode
              - input_boolean.vacation_mode
          - type: conditional
            conditions:
              - entity: input_boolean.xmas_mode
                state: "on"
            card:             
              type: custom:group-card
              card:
                type: entities
                title: Christmas Lights
              group: group.xmas_switches

        
                
        
          
         
          
#      - type: thermostat
#        entity: climate.kit
#      - type: thermostat
#        entity: climate.upstairs
#      - type: thermostat
#        entity: climate.bsmt    
#      - type: iframe
#        url: https://javellino-dexcom-nightscout.herokuapp.com



  - title: Master Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.mbr_sleep_mode
                name: sleep
                tap_action: call-service
                service: script.turn_on
              - type: entity-button
                entity: script.mbr_nightlight_mode
                name: presleep
                tap_action: call-service
                service: script.turn_on
              - type: entity-button
                entity:  script.mbr_awake_in_bed
                name: awake
                icon: mdi:eye-outline
                tap_action: call-service
                service: script.turn_on
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: fan
                icon: mdi:fan
                entity: switch.mbr_fan_108
                tap_action: toggle
              - type: entity-button
                name: ceiling light
                entity:  light.mbr_lights_109
                tap_action: toggle
                icon: mdi:ceiling-light
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.jens_lamp_118
              - type: light
                entity: light.joes_lamp_119
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: bedfan
                tap_action: toggle
                icon: mdi:hotel
                entity: switch.bedfan
              - type: entity-button 
                name: jens blanket
                tap_action: toggle
                entity: switch.wemo_switch_bravo
          - type: thermostat
            entity: climate.upstairs
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.master_bedroom_speaker
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.bedroom
#          - type: entity-filter
#            show_empty: false
#            entities:
#              - media_player.master_bedroom_speaker
#              - media_player.bedroom
#            state_filter:
#              - "off"
 #           card:
 #             - type: media-control
 #               entity:
 #                 - media_player.master_bedroom_speaker
              
        
        
  - title: Basement
    cards:
      - type: picture-glance
        title: Basement
        camera_image: camera.basement
        entities:
          - binary_sensor.dafang_motion_sensor
          - binary_sensor.basement_motion_1_216
          - light.far_lights_234
          - light.stair_lights_232
      - type: thermostat
        entity: climate.bsmt 
#  - title: Dining Room
#    cards:
#      - type: entity-button
#        entity: 
#      - type: light
#        entity: light.joes_lamp_119



  - title: Office
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:bignumber-card
                entity: sensor.temperature_sensor_1_181
                title: Temperature
                from: left
                scale: 30px
                min: 0
                max: 100
                severity:
                  - value: 70
                    style: 'var(--label-badge-green)'
                  - value: 75
                    style: 'var(--label-badge-yellow)'
                  - value: 80
                    style: 'var(--label-badge-red)'
              - type: custom:bignumber-card
                entity: sensor.humidity_sensor_1_183
                title: Humidity
                from: left
                scale: 30px
                min: 0
                max: 100
                severity:
                  - value: 70
                    style: 'var(--label-badge-green)'
                  - value: 75
                    style: 'var(--label-badge-yellow)'
                  - value: 80
                    style: 'var(--label-badge-red)'
              - type: entity-button
                name: Fan
                tap_action: toggle
                icon: mdi:fan
                entity: switch.wemo_switch_charlie
          - type: custom:group-card
            card:
              type: entities
              title: Lights
            group:  group.office_lights
            entity: 
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.office_speaker
        
        
        
        
  - title: Network
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity:  sensor.cpu
                title: Hassbian CPU
              - type: gauge
                entity: sensor.disk_space_used
                title: Hassbian Disk Space
          - type: custom:tracker-card
            title: Updates available
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
      - type: custom:mini-media-player
        artwork: cover
        entity: media_player.spotify
                