resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.0.8
    type: js
  - url: /local/bignumber-card.js
    type: js
  - url: /local/group-card.js
    type: js
  - url: /local/monster-card.js
    type: js
  - url: /local/tracker-card.js?v=0.1.5
    type: js
    
    



title: FredVegas
views:
    # View tab title.
  - title: home
    id: 0
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities:
              - entity: sensor.joe_location
                name: Joe
              - entity: device_tracker.jensiphone
                name: Jen
              - entity: sensor.abby_location
                name: Abby
              - entity: sensor.becca_location
                name: Becca
            state_filter:
              - "home"
            card:
              type: glance
              title: Who's home?
              show_state: false
 #         - type: map
 #           entities:
 #             - zone.home
 #             - device_tracker.joe_joesiphone6s
 #             - device_tracker.abby_abbysiphone
 #             - device_tracker.becca_beccasiphone
      - type: entity-filter
        entities: 
          - binary_sensor.front_door_sensor
          - binary_sensor.garage_door_door_sensor
          - binary_sensor.back_door_slider_sensor
          - binary_sensor.basement_slider_sensor
          - binary_sensor.garage_position 
        state_filter:
          - "on"
        card:
          type: glance
          title: Doors Open
          show_state: false
          show_empty: false
      - type: entity-filter
        entities:
          - entity: binary_sensor.office_motion_161
            name: Office
          - entity: binary_sensor.upstairs_motion_124
            name: Office
          - entity: binary_sensor.basement_motion_1_216
            name: "Basement 1"
          - entity: binary_sensor.dafang_motion_sensor
            name: "Basement 2"
          - entity: binary_sensor.front_hall_motion
            name: Front Hall
          - entity: binary_sensor.ring_front_door_motion
            name: Front Door
        state_filter:
          - "on"
        card:
          type: glance
          title: Motion detected
          show_state: false
      - type: custom:monster-card
        show_empty: false
        card: 
          type: glance
          title: "Low Battery"
          show_state: false
        filter:
          include:
            - domain: binary_sensor
              attributes:
                battery_level: '< 30'
            - domain: lock
              attributes:
                battery_level: '< 30'
            - domain: device_tracker
              attributes:
                battery: '< 30'
      - type: vertical-stack
        aspect_ratio: 75%
        cards:
          - type: entities
            title: Modes
            show_header_toggle: false
            entities:
              - input_boolean.xmas_mode
              - input_boolean.vacation_mode
          - type: conditional
            conditions:
              - entity: input_boolean.xmas_mode
                state: "on"
            card:             
              type: custom:group-card
              card:
                type: entities
                title: Christmas Lights
              group: group.xmas_switches

        
                
        
          
         
          
#      - type: thermostat
#        entity: climate.kit
#      - type: thermostat
#        entity: climate.upstairs
#      - type: thermostat
#        entity: climate.bsmt    
#      - type: iframe
#        url: https://javellino-dexcom-nightscout.herokuapp.com



  - title: Master Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.mbr_sleep_mode
                name: sleep
                tap_action: 
                  action: call-service
                  service: script.turn_on
              - type: entity-button
                entity: script.mbr_nightlight_mode
                name: presleep
                tap_action: 
                  action: call-service
                  service: script.turn_on
              - type: entity-button
                entity:  script.mbr_awake_in_bed
                name: awake
                icon: mdi:eye-outline
                tap_action: 
                  action: call-service
                  service: script.turn_on
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: fan
                icon: mdi:fan
                entity: switch.mbr_fan_108
                tap_action: 
                  action: toggle
              - type: entity-button
                name: ceiling light
                entity:  light.mbr_lights_109
                tap_action: 
                  action: toggle
                icon: mdi:ceiling-light
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.jens_lamp_118
              - type: light
                entity: light.joes_lamp_119
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: bedfan
                tap_action: 
                  action: toggle
                icon: mdi:hotel
                entity: switch.bedfan
              - type: entity-button 
                name: jens blanket
                tap_action: 
                  action: toggle
                entity: switch.wemo_switch_bravo
          - type: thermostat
            entity: climate.upstairs
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.master_bedroom_speaker
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.bedroom
#          - type: entity-filter
#            show_empty: false
#            entities:
#              - media_player.master_bedroom_speaker
#              - media_player.bedroom
#            state_filter:
#              - "off"
 #           card:
 #             - type: media-control
 #               entity:
 #                 - media_player.master_bedroom_speaker
              
  - title: Downstairs
    cards:
      - type: vertical-stack
        cards:
          - type: entity-button
            entity: light.table_light_229
            title: table light
            tap_action: 
              action: toggle
            icon: mdi:ceiling-light
          - type: thermostat
            entity: climate.kit
            title: Kitchen
          - type: custom:mini-media-player
            entity: media_player.kitchen_speaker
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.fireplace_lights_220
                title: fireplace 
                icon: mdi:ceiling-light
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: switch.family_room_fan_213
                title: fan
                icon: mdi:fan
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: switch.tplink_plug
                title: end table
                icon: mdi:lamp
                tap_action: 
                  action: toggle
          - type: horizontal-stack
            cards: 
              - type: light
                entity: light.joe_family_room_lamp
                name: Joes lamp
              - type: light
                entity: light.jen_family_room_lamp
                name: Jens lamp
                
                
      - type: vertical-stack
        cards:

          - type: custom:mini-media-player
            entity: media_player.family_room
            title: Roku
            artwork: cover
          - type: custom:mini-media-player
            entity: media_player.fluffy
            title: Fluffy
            artwork: cover
        
        
        
  - title: Basement
    cards:
      - type: picture-glance
        title: Basement
        camera_image: camera.basement
        entities:
          - binary_sensor.dafang_motion_sensor
          - binary_sensor.basement_motion_1_216
          - light.far_lights_234
          - light.stair_lights_232
      - type: thermostat
        entity: climate.bsmt 
      - type: custom:mini-media-player
        artwork: cover
        entity: media_player.apple_tv
        
        
 
#  - title: Dining Room
#    cards:
#      - type: entity-button
#        entity: 
#      - type: light
#        entity: light.joes_lamp_119



  - title: Office
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:bignumber-card
                entity: sensor.temperature_sensor_1_181
                title: Temperature
                from: left
                min: 0
                max: 100
                severity:
                  - value: 70
                    style: 'var(--label-badge-green)'
                  - value: 75
                    style: 'var(--label-badge-yellow)'
                  - value: 80
                    style: 'var(--label-badge-red)'
              - type: custom:bignumber-card
                entity: sensor.humidity_sensor_1_183
                title: Humidity
                from: left
                min: 0
                max: 100
                severity:
                  - value: 70
                    style: 'var(--label-badge-green)'
                  - value: 75
                    style: 'var(--label-badge-yellow)'
                  - value: 80
                    style: 'var(--label-badge-red)'
              - type: entity-button
                name: Fan
                tap_action: toggle
                icon: mdi:fan
                entity: switch.wemo_switch_charlie
          - type: custom:group-card
            card:
              type: entities
              title: Lights
            group:  group.office_lights
            entity: 
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.office_speaker
        
        
  - title: Outside
    cards:
      - type: vertical-stack
        cards:
          - type: entity-filter
            entities: 
              - binary_sensor.front_door_sensor
              - binary_sensor.garage_door_door_sensor
              - binary_sensor.back_door_slider_sensor
              - binary_sensor.basement_slider_sensor
              - binary_sensor.garage_position 
            state_filter:
              - "on"
            card:
              type: glance
              title: Doors Open
            show_state: false
            show_empty: false
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: Driveway
                icon: mdi:car-side
                entity: light.driveway_lights_65
                tap_action: 
                  action: toggle
              - type: entity-button
                name: Front Porch
                icon: mdi:door
                entity: light.front_porch_lights_63
                tap_action: 
                  action: toggle
              - type: entity-button
                name: Back Deck
                icon: mdi:ceiling-light
                entity: light.deck_light_228
                tap_action: 
                  action: toggle   

          - type: picture-glance
            camera_image: camera.front_door
            title: Front Door
            entities:
              - binary_sensor.ring_front_door_motion
              - binary_sensor.ring_front_door_ding
              - entity: lock.front_door_lock_4
                tap_action: 
                  action: toggle
            show_state: false
          - type: entity-button
            entity: switch.garage_door_99
            title: Garage door
            icon: mdi:garage
            tap_action:
              action: toggle
            
  - title: Network
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.disk_space_used
                name: Hassbian Disk Space
              - type: gauge
                entity: sensor.gonzo_disk_space
                name: Gonzo Disk space
              - type: gauge
                entity: sensor.raspberrypi_disk_space
                name: Rpi Disk Space  
              - type: gauge
                entity: sensor.data_space
                name: Data Storage
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.cpu
                name: Hassbian CPU
              - type: gauge
                entity: sensor.gonzo_cpu
                name: Gonzo CPU
              - type: gauge
                entity: sensor.raspberrypi_cpu
                name: Rpi CPU
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: OpenVPN
                entity:  binary_sensor.openvpn
                tap_action: 
                  action: call-service
                  service: shell_command.restart_openvpn
              - type: entity-button
                name: transmission
                entity: binary_sensor.transmission_status
                tap_action: 
                  action: call-service
                  service: shell_command.restart_transmission
          - type: custom:tracker-card
            title: Custom Updates available
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.spotify

                