alias: 'kids to/from anywhere'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.abby_location
  - platform: state
    entity_id: sensor.becca_location
    
condition:
  condition: template
  value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
action:
  service: notify.pb 
  data_template:
    message: "{{ trigger.entity_id.attributes.friendly_name }} has gone from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}."

