alias: 'Abby to/from anywhere'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.abby_location
condition:
  condition: template
  value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
action:
  service: notify.pb 
  data_template:
    message: "Abby has gone from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}."

