alias: 'Joes away'
initial_state: 'on'
trigger:
  platform: state
  entity_id: device_tracker.joe_joesiphone6s
  from: 'home'
#  to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: time
      before: '12:00:00'
    - condition: state
      entity_id: calendar.joe_to_work
      state: 'on'
action:
  - service: light.turn_off
    entity_id: group.office_lights
  - service: light.turn_off
    entity_id: group.outside_lights
  - service: notify.pb
    data_template: 
      message: "to VRE: {{ states.sensor.home_to_vre_lot.state }} min, to Work: {{ states.sensor.home_to_work.state }} min"
