alias: 'reminder to pick up becca at gymnastics'
initial_state: 'on'
trigger:
  platform: time
  at: '15:45:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.becca_pick_up
      state: 'on'
    - condition: state
      entity_id: device_tracker.joe_joesiphone6s
      state: 'home'
action:
  - service: notify.pb
    data_template:
      message: "its now {{states.sensor.time.state}}, you should have left to get Becca!"
  - service: light.turn_on
    data:
      entity_id: light.joe_family_room_lamp
      flash: long


