script:
  reset_motion_boolean:
    alias: "reset motion boolean"
    sequence: 
      - service: input_boolean.turn_on
        entity_id: input_boolean.front_hall_motion
      - delay: 00:05:00
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_hall_motion

binary_sensor:
  - platform: template
    sensors:
      front_hall_motion:
        friendly_name: Front Hall Motion
        value_template: "{% if is_state(states.input_boolean.front_hall_motion.state, 'on') %} on {% else %} off {% endif %}}"
        device_class: motion
        
      
input_boolean:
  front_hall_motion:

    
automation:
  - alias: "reset front hall motion boolean"
    trigger:
      platform: state
      entity_id: binary_sensor.front_hall_motion_raw
      to: 'on'
    action:
      - service: script.turn_off
        entity_id: script.reset_motion_boolean
      - service: script.turn_on
        entity_id: script.reset_motion_boolean
    
  - alias: 'detect hall motion'
    trigger: 
      platform: state
      entity_id: input_boolean.front_hall_motion
      to: 'on'
    condition: 
      condition: or
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
  
    action: 
      service: light.turn_on
      entity_id: light.living_room_lamp
      
  - alias: 'stop detecting motion turn off lamp'
    trigger: 
      platform: state
      entity_id: input_boolean.front_hall_motion
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.living_room_lamp